// angular-admin/src/app/pages/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="dashboard">
      <h1>首页</h1>
      <div class="cards">
        <div class="card">
          <h3>用户数量</h3>
          <div class="statistic">1,024</div>
        </div>
        <div class="card">
          <h3>在线用户</h3>
          <div class="statistic">128</div>
        </div>
        <div class="card">
          <h3>今日访问</h3>
          <div class="statistic">3,456</div>
        </div>
        <div class="card">
          <h3>系统消息</h3>
          <div class="statistic">12</div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .dashboard h1 {
      margin-bottom: 20px;
    }
    .cards {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 20px;
    }
    .card {
      background: #fff;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 2px 12px rgba(0, 0, 0, 0.1);
    }
    .card h3 {
      color: #909399;
      font-size: 14px;
      margin-bottom: 10px;
    }
    .statistic {
      font-size: 32px;
      font-weight: bold;
      color: #409eff;
      text-align: center;
    }
  `],
})
export class DashboardComponent {}

// vue-admin/src/views/dashboard/index.vue
<template>
  <div class="dashboard-container">
    <el-row :gutter="20">
      <el-col :span="6">
        <el-card shadow="hover">
          <template #header>用户数量</template>
          <div class="statistic">1,024</div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card shadow="hover">
          <template #header>在线用户</template>
          <div class="statistic">128</div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card shadow="hover">
          <template #header>今日访问</template>
          <div class="statistic">3,456</div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card shadow="hover">
          <template #header>系统消息</template>
          <div class="statistic">12</div>
        </el-card>
      </el-col>
    </el-row>

    <el-row :gutter="20" style="margin-top: 20px">
      <el-col :span="12">
        <el-card>
          <template #header>快捷操作</template>
          <el-space wrap>
            <el-button @click="$router.push('/system/user')">用户管理</el-button>
            <el-button @click="$router.push('/system/role')">角色管理</el-button>
            <el-button @click="$router.push('/system/menu')">菜单管理</el-button>
            <el-button @click="$router.push('/monitor/server')">服务监控</el-button>
          </el-space>
        </el-card>
      </el-col>
      <el-col :span="12">
        <el-card>
          <template #header>系统信息</template>
          <el-descriptions :column="1" border>
            <el-descriptions-item label="系统名称">Admin Pro</el-descriptions-item>
            <el-descriptions-item label="技术栈">Vue 3 + Element Plus</el-descriptions-item>
            <el-descriptions-item label="当前版本">v1.0.0</el-descriptions-item>
          </el-descriptions>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script setup lang="ts">
</script>

<style lang="scss" scoped>
.dashboard-container {
  padding: 20px;
}

.statistic {
  font-size: 32px;
  font-weight: bold;
  color: #409eff;
  text-align: center;
}
</style>
