// angular-admin/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { appConfig } from '../../config/app.config';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="login-container">
      <div class="login-form">
        <h2 class="title">{{ title }}</h2>
        <div class="form-item">
          <input
            type="text"
            [(ngModel)]="username"
            placeholder="请输入用户名"
            (keyup.enter)="login()"
          />
        </div>
        <div class="form-item">
          <input
            type="password"
            [(ngModel)]="password"
            placeholder="请输入密码"
            (keyup.enter)="login()"
          />
        </div>
        <div *ngIf="error" class="error">{{ error }}</div>
        <button (click)="login()" [disabled]="loading" class="login-btn">
          {{ loading ? '登录中...' : '登录' }}
        </button>
      </div>
    </div>
  `,
  styles: [`
    .login-container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    }
    .login-form {
      width: 400px;
      padding: 40px;
      background: #fff;
      border-radius: 12px;
      box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
    }
    .title {
      text-align: center;
      margin-bottom: 30px;
      font-size: 24px;
      color: #333;
    }
    .form-item {
      margin-bottom: 20px;
    }
    input {
      width: 100%;
      padding: 12px;
      border: 1px solid #dcdfe6;
      border-radius: 4px;
      font-size: 14px;
      outline: none;
    }
    input:focus {
      border-color: #409eff;
    }
    .error {
      color: #f56c6c;
      font-size: 12px;
      margin-bottom: 10px;
    }
    .login-btn {
      width: 100%;
      padding: 12px;
      background: #409eff;
      color: #fff;
      border: none;
      border-radius: 4px;
      font-size: 16px;
      cursor: pointer;
    }
    .login-btn:hover {
      background: #66b1ff;
    }
    .login-btn:disabled {
      opacity: 0.7;
      cursor: not-allowed;
    }
  `],
})
export class LoginComponent {
  title = appConfig.title;
  username = 'admin';
  password = 'admin123';
  loading = false;
  error = '';

  constructor(private authService: AuthService, private router: Router) {}

  login(): void {
    if (!this.username || !this.password) {
      this.error = '请输入用户名和密码';
      return;
    }

    this.loading = true;
    this.error = '';

    this.authService.login(this.username, this.password).subscribe({
      next: () => {
        this.router.navigate(['/']);
      },
      error: (err) => {
        this.error = err.error?.message || '登录失败';
        this.loading = false;
      },
    });
  }
}

// vue2-admin/src/views/login/index.vue
<template>
  <div class="login-container">
    <el-form ref="loginForm" :model="loginForm" :rules="loginRules" class="login-form">
      <div class="title-container">
        <h3 class="title">{{ appConfig.title }}</h3>
      </div>
      <el-form-item prop="username">
        <el-input
          v-model="loginForm.username"
          placeholder="请输入用户名"
          prefix-icon="el-icon-user"
          size="large"
        />
      </el-form-item>
      <el-form-item prop="password">
        <el-input
          v-model="loginForm.password"
          type="password"
          placeholder="请输入密码"
          prefix-icon="el-icon-lock"
          size="large"
          show-password
          @keyup.enter.native="handleLogin"
        />
      </el-form-item>
      <el-button :loading="loading" type="primary" size="large" style="width: 100%" @click="handleLogin">
        登录
      </el-button>
    </el-form>
  </div>
</template>

<script>
import { appConfig } from '@/config/app'

export default {
  name: 'Login',
  data() {
    return {
      appConfig,
      loading: false,
      loginForm: {
        username: 'admin',
        password: 'admin123',
      },
      loginRules: {
        username: [{ required: true, message: '请输入用户名', trigger: 'blur' }],
        password: [{ required: true, message: '请输入密码', trigger: 'blur' }],
      },
    }
  },
  methods: {
    handleLogin() {
      this.$refs.loginForm.validate(async valid => {
        if (!valid) return

        this.loading = true
        try {
          await this.$store.dispatch('login', this.loginForm)
          this.$message.success('登录成功')
          this.$router.push('/')
        } catch (error) {
          this.$message.error(error.message || '登录失败')
        } finally {
          this.loading = false
        }
      })
    },
  },
}
</script>

<style lang="scss" scoped>
.login-container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.login-form {
  width: 400px;
  padding: 40px;
  background: #fff;
  border-radius: 12px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
}

.title-container {
  text-align: center;
  margin-bottom: 30px;

  .title {
    font-size: 24px;
    color: #333;
  }
}
</style>
