// angular-admin/src/app/layouts/layout.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { ApiService } from '../../services/api.service';
import { appConfig } from '../../config/app.config';

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div class="app-wrapper" [class.sidebar-collapsed]="!sidebarOpened">
      <!-- 侧边栏 -->
      <div class="sidebar">
        <div class="logo">
          <img [src]="logo" alt="Logo" />
          <span *ngIf="sidebarOpened" class="title">{{ title }}</span>
        </div>
        <nav class="menu">
          <a routerLink="/dashboard" routerLinkActive="active" class="menu-item">
            <span class="icon">🏠</span>
            <span *ngIf="sidebarOpened">首页</span>
          </a>
          <div class="menu-group">
            <div class="menu-group-title" *ngIf="sidebarOpened">系统管理</div>
            <a routerLink="/system/user" routerLinkActive="active" class="menu-item">
              <span class="icon">👤</span>
              <span *ngIf="sidebarOpened">用户管理</span>
            </a>
            <a routerLink="/system/role" routerLinkActive="active" class="menu-item">
              <span class="icon">🔑</span>
              <span *ngIf="sidebarOpened">角色管理</span>
            </a>
            <a routerLink="/system/menu" routerLinkActive="active" class="menu-item">
              <span class="icon">📋</span>
              <span *ngIf="sidebarOpened">菜单管理</span>
            </a>
          </div>
        </nav>
        <div class="collapse-btn" (click)="toggleSidebar()">
          {{ sidebarOpened ? '◀' : '▶' }}
        </div>
      </div>

      <!-- 主内容区 -->
      <div class="main">
        <header class="header">
          <div></div>
          <div class="user-info">
            <span>{{ userInfo?.nickname }}</span>
            <button (click)="logout()" class="logout-btn">退出</button>
          </div>
        </header>
        <main class="content">
          <router-outlet></router-outlet>
        </main>
      </div>
    </div>
  `,
  styles: [`
    .app-wrapper {
      display: flex;
      height: 100vh;
    }
    .sidebar {
      width: 210px;
      background: #304156;
      display: flex;
      flex-direction: column;
      transition: width 0.3s;
    }
    .sidebar-collapsed .sidebar {
      width: 64px;
    }
    .logo {
      height: 50px;
      display: flex;
      align-items: center;
      justify-content: center;
      background: #2b2f3a;
    }
    .logo img {
      width: 32px;
      height: 32px;
    }
    .logo .title {
      color: #fff;
      margin-left: 10px;
      font-weight: 600;
    }
    .menu {
      flex: 1;
      overflow-y: auto;
    }
    .menu-item {
      display: flex;
      align-items: center;
      padding: 12px 20px;
      color: #bfcbd9;
      text-decoration: none;
      cursor: pointer;
    }
    .menu-item:hover,
    .menu-item.active {
      background: #263445;
      color: #409eff;
    }
    .menu-item .icon {
      margin-right: 10px;
    }
    .menu-group-title {
      padding: 12px 20px 4px;
      color: #909399;
      font-size: 12px;
    }
    .collapse-btn {
      height: 48px;
      display: flex;
      align-items: center;
      justify-content: center;
      background: #2b2f3a;
      color: #bfcbd9;
      cursor: pointer;
      border-top: 1px solid rgba(255, 255, 255, 0.1);
    }
    .collapse-btn:hover {
      color: #409eff;
    }
    .main {
      flex: 1;
      display: flex;
      flex-direction: column;
      overflow: hidden;
    }
    .header {
      height: 50px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 0 15px;
      background: #fff;
      box-shadow: 0 1px 4px rgba(0, 21, 41, 0.08);
    }
    .user-info {
      display: flex;
      align-items: center;
      gap: 10px;
    }
    .logout-btn {
      padding: 4px 12px;
      border: 1px solid #f56c6c;
      color: #f56c6c;
      background: transparent;
      border-radius: 4px;
      cursor: pointer;
    }
    .content {
      flex: 1;
      padding: 15px;
      overflow-y: auto;
      background: #f0f2f5;
    }
  `],
})
export class LayoutComponent implements OnInit {
  title = appConfig.title;
  logo = appConfig.logo;
  sidebarOpened = true;
  userInfo: any;

  constructor(
    private authService: AuthService,
    private apiService: ApiService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.userInfo = this.authService.getUserInfo();
  }

  toggleSidebar(): void {
    this.sidebarOpened = !this.sidebarOpened;
  }

  logout(): void {
    this.authService.logout();
  }
}

// next-admin/src/app/(dashboard)/layout.tsx
'use client';

import { useEffect, useState } from 'react';
import { useRouter, usePathname } from 'next/navigation';
import Cookies from 'js-cookie';
import Link from 'next/link';
import { useAuthStore } from '@/stores/auth';
import { appConfig } from '@/config/app';

const menuItems = [
  { path: '/dashboard', label: '首页', icon: '🏠' },
  {
    label: '系统管理',
    icon: '⚙️',
    children: [
      { path: '/system/user', label: '用户管理' },
      { path: '/system/role', label: '角色管理' },
      { path: '/system/menu', label: '菜单管理' },
      { path: '/system/dept', label: '部门管理' },
    ],
  },
  {
    label: '系统监控',
    icon: '📊',
    children: [
      { path: '/monitor/online', label: '在线用户' },
      { path: '/monitor/server', label: '服务监控' },
    ],
  },
];

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  const router = useRouter();
  const pathname = usePathname();
  const { userInfo, setUserInfo, logout } = useAuthStore();
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const token = Cookies.get('accessToken');
    if (!token) {
      router.push('/login');
      return;
    }
    const stored = localStorage.getItem('userInfo');
    if (stored) {
      setUserInfo(JSON.parse(stored));
    }
  }, [router, setUserInfo]);

  if (!mounted) return null;

  const handleLogout = () => {
    logout();
    router.push('/login');
  };

  return (
    <div className="flex h-screen bg-gray-100 dark:bg-gray-900">
      {/* 侧边栏 */}
      <aside className={`${sidebarOpen ? 'w-64' : 'w-16'} bg-gray-800 text-white transition-all duration-300 flex flex-col`}>
        <div className="p-4 flex-shrink-0">
          <h1 className={`text-xl font-bold ${!sidebarOpen && 'hidden'}`}>{appConfig.title}</h1>
        </div>
        <nav className="mt-4 flex-1 overflow-y-auto">
          {menuItems.map((item, index) => (
            <div key={index}>
              {item.children ? (
                <div>
                  <div className="px-4 py-2 text-gray-400 text-sm">{sidebarOpen ? item.label : item.icon}</div>
                  {item.children.map((child) => (
                    <Link
                      key={child.path}
                      href={child.path}
                      className={`block px-8 py-2 text-sm hover:bg-gray-700 ${pathname === child.path ? 'bg-gray-700 text-white' : 'text-gray-300'}`}
                    >
                      {child.label}
                    </Link>
                  ))}
                </div>
              ) : (
                <Link
                  href={item.path}
                  className={`block px-4 py-2 hover:bg-gray-700 ${pathname === item.path ? 'bg-gray-700 text-white' : 'text-gray-300'}`}
                >
                  {sidebarOpen ? item.label : item.icon}
                </Link>
              )}
            </div>
          ))}
        </nav>
        {/* 折叠/展开按钮 */}
        <div
          className="h-12 flex items-center justify-center bg-gray-900 cursor-pointer hover:bg-gray-700 transition-colors border-t border-gray-700 flex-shrink-0"
          onClick={() => setSidebarOpen(!sidebarOpen)}
        >
          <span className="text-lg">{sidebarOpen ? '◀' : '▶'}</span>
        </div>
      </aside>

      {/* 主内容区 */}
      <div className="flex-1 flex flex-col overflow-hidden">
        {/* 顶部导航 */}
        <header className="bg-white dark:bg-gray-800 shadow-sm h-14 flex items-center justify-between px-4">
          <div></div>
          <div className="flex items-center gap-4">
            <span className="text-sm text-gray-600 dark:text-gray-300">{userInfo?.nickname}</span>
            <button onClick={handleLogout} className="text-sm text-red-500 hover:text-red-700">
              退出
            </button>
          </div>
        </header>

        {/* 页面内容 */}
        <main className="flex-1 overflow-auto p-6">
          {children}
        </main>
      </div>
    </div>
  );
}
