// vue2-admin/src/views/system/user/index.vue
<template>
  <div class="app-container">
    <!-- 搜索区域 -->
    <el-form :model="queryParams" ref="queryForm" :inline="true">
      <el-form-item label="用户名" prop="username">
        <el-input v-model="queryParams.username" placeholder="请输入用户名" @keyup.enter.native="handleQuery" />
      </el-form-item>
      <el-form-item label="状态" prop="status">
        <el-select v-model="queryParams.status" placeholder="请选择状态" clearable>
          <el-option label="正常" :value="0" />
          <el-option label="停用" :value="1" />
        </el-select>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="handleQuery">搜索</el-button>
        <el-button @click="resetQuery">重置</el-button>
      </el-form-item>
    </el-form>

    <!-- 操作按钮 -->
    <el-row :gutter="10" class="mb8">
      <el-col :span="1.5">
        <el-button type="primary" plain @click="handleAdd">新增</el-button>
      </el-col>
    </el-row>

    <!-- 数据表格 -->
    <el-table v-loading="loading" :data="userList">
      <el-table-column type="index" width="50" />
      <el-table-column prop="username" label="用户名" width="120" />
      <el-table-column prop="nickname" label="昵称" width="120" />
      <el-table-column prop="dept.name" label="部门" width="120" />
      <el-table-column prop="phone" label="手机号" width="120" />
      <el-table-column prop="status" label="状态" width="80">
        <template slot-scope="scope">
          <el-tag :type="scope.row.status === 0 ? 'success' : 'danger'">
            {{ scope.row.status === 0 ? '正常' : '停用' }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column prop="createdAt" label="创建时间" width="160" />
      <el-table-column label="操作" width="200">
        <template slot-scope="scope">
          <el-button type="text" @click="handleUpdate(scope.row)">修改</el-button>
          <el-button type="text" @click="handleDelete(scope.row)">删除</el-button>
          <el-button type="text" @click="handleResetPwd(scope.row)">重置密码</el-button>
        </template>
      </el-table-column>
    </el-table>

    <!-- 分页 -->
    <el-pagination
      v-show="total > 0"
      :current-page.sync="queryParams.pageNum"
      :page-size.sync="queryParams.pageSize"
      :total="total"
      :page-sizes="[10, 20, 50, 100]"
      layout="total, sizes, prev, pager, next, jumper"
      @size-change="getList"
      @current-change="getList"
    />

    <!-- 新增/修改对话框 -->
    <el-dialog :title="dialogTitle" :visible.sync="dialogVisible" width="600px">
      <el-form ref="userForm" :model="form" :rules="rules" label-width="80px">
        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item label="用户名" prop="username">
              <el-input v-model="form.username" placeholder="请输入用户名" :disabled="!!form.id" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="昵称" prop="nickname">
              <el-input v-model="form.nickname" placeholder="请输入昵称" />
            </el-form-item>
          </el-col>
          <el-col :span="12" v-if="!form.id">
            <el-form-item label="密码" prop="password">
              <el-input v-model="form.password" type="password" placeholder="请输入密码" show-password />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="手机号" prop="phone">
              <el-input v-model="form.phone" placeholder="请输入手机号" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="邮箱" prop="email">
              <el-input v-model="form.email" placeholder="请输入邮箱" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="状态">
              <el-radio-group v-model="form.status">
                <el-radio :label="0">正常</el-radio>
                <el-radio :label="1">停用</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="角色">
              <el-select v-model="form.roleIds" multiple placeholder="请选择角色">
                <el-option v-for="item in roleOptions" :key="item.id" :label="item.name" :value="item.id" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="24">
            <el-form-item label="备注">
              <el-input v-model="form.remark" type="textarea" placeholder="请输入备注" />
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
      <div slot="footer">
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="submitForm">确定</el-button>
      </div>
    </el-dialog>
  </div>
</template>

<script>
import { listUser, getUser, addUser, updateUser, deleteUser, resetUserPwd, getAllRole } from '@/api/system'

export default {
  name: 'UserManage',
  data() {
    return {
      loading: false,
      userList: [],
      total: 0,
      dialogVisible: false,
      dialogTitle: '',
      roleOptions: [],
      queryParams: {
        pageNum: 1,
        pageSize: 10,
        username: '',
        status: undefined,
      },
      form: {
        id: undefined,
        username: '',
        nickname: '',
        password: '',
        phone: '',
        email: '',
        status: 0,
        roleIds: [],
        remark: '',
      },
      rules: {
        username: [{ required: true, message: '请输入用户名', trigger: 'blur' }],
        nickname: [{ required: true, message: '请输入昵称', trigger: 'blur' }],
        password: [{ required: true, message: '请输入密码', trigger: 'blur' }],
      },
    }
  },
  created() {
    this.getList()
    this.getRoles()
  },
  methods: {
    async getList() {
      this.loading = true
      try {
        const res = await listUser(this.queryParams)
        this.userList = res.data.list
        this.total = res.data.total
      } finally {
        this.loading = false
      }
    },
    async getRoles() {
      const res = await getAllRole()
      this.roleOptions = res.data
    },
    handleQuery() {
      this.queryParams.pageNum = 1
      this.getList()
    },
    resetQuery() {
      this.queryParams.username = ''
      this.queryParams.status = undefined
      this.handleQuery()
    },
    handleAdd() {
      this.dialogTitle = '新增用户'
      this.form = {
        id: undefined,
        username: '',
        nickname: '',
        password: '',
        phone: '',
        email: '',
        status: 0,
        roleIds: [],
        remark: '',
      }
      this.dialogVisible = true
    },
    async handleUpdate(row) {
      this.dialogTitle = '修改用户'
      const res = await getUser(row.id)
      this.form = res.data
      this.dialogVisible = true
    },
    handleDelete(row) {
      this.$confirm('确认删除该用户?', '提示', { type: 'warning' }).then(async () => {
        await deleteUser(row.id)
        this.$message.success('删除成功')
        this.getList()
      })
    },
    handleResetPwd(row) {
      this.$prompt('请输入新密码', '重置密码', {
        confirmButtonText: '确定',
        cancelButtonText: '取消',
        inputValue: '123456',
      }).then(async ({ value }) => {
        await resetUserPwd(row.id, value)
        this.$message.success('重置成功')
      })
    },
    async submitForm() {
      if (this.form.id) {
        await updateUser(this.form.id, this.form)
        this.$message.success('修改成功')
      } else {
        await addUser(this.form)
        this.$message.success('新增成功')
      }
      this.dialogVisible = false
      this.getList()
    },
  },
}
</script>

// angular-admin/src/app/pages/system/user/user.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../../services/api.service';

@Component({
  selector: 'app-user',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="app-container">
      <div class="search-bar">
        <input [(ngModel)]="queryParams.username" placeholder="用户名" />
        <button (click)="getList()" class="btn-primary">搜索</button>
        <button (click)="resetQuery()" class="btn-default">重置</button>
        <button (click)="handleAdd()" class="btn-primary">新增</button>
      </div>

      <table class="data-table">
        <thead>
          <tr>
            <th>用户名</th>
            <th>昵称</th>
            <th>手机号</th>
            <th>状态</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let user of userList">
            <td>{{ user.username }}</td>
            <td>{{ user.nickname }}</td>
            <td>{{ user.phone }}</td>
            <td>
              <span [class]="user.status === 0 ? 'tag-success' : 'tag-danger'">
                {{ user.status === 0 ? '正常' : '停用' }}
              </span>
            </td>
            <td>
              <button (click)="handleUpdate(user)" class="btn-text">修改</button>
              <button (click)="handleDelete(user)" class="btn-text-danger">删除</button>
            </td>
          </tr>
        </tbody>
      </table>

      <div class="pagination">
        <span>共 {{ total }} 条</span>
      </div>

      <!-- 对话框 -->
      <div *ngIf="dialogVisible" class="dialog-overlay" (click)="dialogVisible = false">
        <div class="dialog" (click)="$event.stopPropagation()">
          <h3>{{ dialogTitle }}</h3>
          <div class="form-group">
            <label>用户名</label>
            <input [(ngModel)]="form.username" [disabled]="!!form.id" />
          </div>
          <div class="form-group">
            <label>昵称</label>
            <input [(ngModel)]="form.nickname" />
          </div>
          <div class="form-group" *ngIf="!form.id">
            <label>密码</label>
            <input type="password" [(ngModel)]="form.password" />
          </div>
          <div class="form-group">
            <label>手机号</label>
            <input [(ngModel)]="form.phone" />
          </div>
          <div class="form-group">
            <label>状态</label>
            <select [(ngModel)]="form.status">
              <option [value]="0">正常</option>
              <option [value]="1">停用</option>
            </select>
          </div>
          <div class="dialog-footer">
            <button (click)="dialogVisible = false">取消</button>
            <button (click)="submitForm()" class="btn-primary">确定</button>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .app-container { background: #fff; padding: 20px; border-radius: 8px; }
    .search-bar { margin-bottom: 20px; display: flex; gap: 10px; }
    .search-bar input { padding: 8px 12px; border: 1px solid #dcdfe6; border-radius: 4px; }
    .data-table { width: 100%; border-collapse: collapse; }
    .data-table th, .data-table td { padding: 12px; border-bottom: 1px solid #ebeef5; text-align: left; }
    .data-table th { background: #f5f7fa; }
    .tag-success { color: #67c23a; }
    .tag-danger { color: #f56c6c; }
    .btn-primary { padding: 8px 16px; background: #409eff; color: #fff; border: none; border-radius: 4px; cursor: pointer; }
    .btn-default { padding: 8px 16px; border: 1px solid #dcdfe6; border-radius: 4px; cursor: pointer; }
    .btn-text { color: #409eff; background: none; border: none; cursor: pointer; }
    .btn-text-danger { color: #f56c6c; background: none; border: none; cursor: pointer; }
    .pagination { margin-top: 20px; }
    .dialog-overlay { position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,0.5); display: flex; align-items: center; justify-content: center; z-index: 1000; }
    .dialog { background: #fff; padding: 20px; border-radius: 8px; width: 500px; }
    .dialog h3 { margin-bottom: 20px; }
    .form-group { margin-bottom: 15px; }
    .form-group label { display: block; margin-bottom: 5px; color: #606266; }
    .form-group input, .form-group select { width: 100%; padding: 8px 12px; border: 1px solid #dcdfe6; border-radius: 4px; }
    .dialog-footer { text-align: right; margin-top: 20px; }
    .dialog-footer button { margin-left: 10px; }
  `],
})
export class UserComponent implements OnInit {
  userList: any[] = [];
  total = 0;
  queryParams = { pageNum: 1, pageSize: 10, username: '' };
  dialogVisible = false;
  dialogTitle = '';
  form: any = { id: undefined, username: '', nickname: '', password: '', phone: '', status: 0 };

  constructor(private api: ApiService) {}

  ngOnInit(): void {
    this.getList();
  }

  getList(): void {
    this.api.listUser(this.queryParams).subscribe((res) => {
      this.userList = res.data.list;
      this.total = res.data.total;
    });
  }

  resetQuery(): void {
    this.queryParams.username = '';
    this.getList();
  }

  handleAdd(): void {
    this.dialogTitle = '新增用户';
    this.form = { id: undefined, username: '', nickname: '', password: '', phone: '', status: 0 };
    this.dialogVisible = true;
  }

  handleUpdate(row: any): void {
    this.dialogTitle = '修改用户';
    this.form = { ...row };
    this.dialogVisible = true;
  }

  handleDelete(row: any): void {
    if (confirm('确认删除该用户?')) {
      this.api.deleteUser(row.id).subscribe(() => {
        this.getList();
      });
    }
  }

  submitForm(): void {
    if (this.form.id) {
      this.api.updateUser(this.form.id, this.form).subscribe(() => {
        this.dialogVisible = false;
        this.getList();
      });
    } else {
      this.api.addUser(this.form).subscribe(() => {
        this.dialogVisible = false;
        this.getList();
      });
    }
  }
}
