// angular-admin/src/app/pages/system/menu/menu.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../../services/api.service';

@Component({
  selector: 'app-menu',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="app-container">
      <div class="search-bar">
        <input [(ngModel)]="queryParams.menuName" placeholder="菜单名称" />
        <button (click)="getList()" class="btn-primary">搜索</button>
        <button (click)="handleAdd()" class="btn-primary">新增</button>
      </div>

      <table class="data-table">
        <thead>
          <tr>
            <th>菜单名称</th>
            <th>类型</th>
            <th>路由路径</th>
            <th>权限标识</th>
            <th>状态</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <ng-container *ngFor="let menu of menuList">
            <tr>
              <td>{{ menu.name }}</td>
              <td>
                <span *ngIf="menu.type === 0">目录</span>
                <span *ngIf="menu.type === 1">菜单</span>
                <span *ngIf="menu.type === 2">按钮</span>
              </td>
              <td>{{ menu.path }}</td>
              <td>{{ menu.permission }}</td>
              <td>
                <span [class]="menu.status === 0 ? 'tag-success' : 'tag-danger'">
                  {{ menu.status === 0 ? '正常' : '停用' }}
                </span>
              </td>
              <td>
                <button (click)="handleAdd(menu)" class="btn-text">新增</button>
                <button (click)="handleUpdate(menu)" class="btn-text">修改</button>
                <button (click)="handleDelete(menu)" class="btn-text-danger">删除</button>
              </td>
            </tr>
            <ng-container *ngIf="menu.children">
              <tr *ngFor="let child of menu.children">
                <td style="padding-left: 30px">{{ child.name }}</td>
                <td>
                  <span *ngIf="child.type === 1">菜单</span>
                  <span *ngIf="child.type === 2">按钮</span>
                </td>
                <td>{{ child.path }}</td>
                <td>{{ child.permission }}</td>
                <td>
                  <span [class]="child.status === 0 ? 'tag-success' : 'tag-danger'">
                    {{ child.status === 0 ? '正常' : '停用' }}
                  </span>
                </td>
                <td>
                  <button (click)="handleUpdate(child)" class="btn-text">修改</button>
                  <button (click)="handleDelete(child)" class="btn-text-danger">删除</button>
                </td>
              </tr>
            </ng-container>
          </ng-container>
        </tbody>
      </table>

      <div *ngIf="dialogVisible" class="dialog-overlay" (click)="dialogVisible = false">
        <div class="dialog" (click)="$event.stopPropagation()">
          <h3>{{ dialogTitle }}</h3>
          <div class="form-group">
            <label>菜单类型</label>
            <select [(ngModel)]="form.type">
              <option [value]="0">目录</option>
              <option [value]="1">菜单</option>
              <option [value]="2">按钮</option>
            </select>
          </div>
          <div class="form-group">
            <label>菜单名称</label>
            <input [(ngModel)]="form.name" />
          </div>
          <div class="form-group" *ngIf="form.type !== 2">
            <label>路由路径</label>
            <input [(ngModel)]="form.path" />
          </div>
          <div class="form-group" *ngIf="form.type === 1">
            <label>组件路径</label>
            <input [(ngModel)]="form.component" />
          </div>
          <div class="form-group" *ngIf="form.type !== 0">
            <label>权限标识</label>
            <input [(ngModel)]="form.permission" />
          </div>
          <div class="form-group">
            <label>状态</label>
            <select [(ngModel)]="form.status">
              <option [value]="0">正常</option>
              <option [value]="1">停用</option>
            </select>
          </div>
          <div class="dialog-footer">
            <button (click)="dialogVisible = false">取消</button>
            <button (click)="submitForm()" class="btn-primary">确定</button>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .app-container { background: #fff; padding: 20px; border-radius: 8px; }
    .search-bar { margin-bottom: 20px; display: flex; gap: 10px; }
    .search-bar input { padding: 8px 12px; border: 1px solid #dcdfe6; border-radius: 4px; }
    .data-table { width: 100%; border-collapse: collapse; }
    .data-table th, .data-table td { padding: 12px; border-bottom: 1px solid #ebeef5; text-align: left; }
    .data-table th { background: #f5f7fa; }
    .tag-success { color: #67c23a; }
    .tag-danger { color: #f56c6c; }
    .btn-primary { padding: 8px 16px; background: #409eff; color: #fff; border: none; border-radius: 4px; cursor: pointer; }
    .btn-text { color: #409eff; background: none; border: none; cursor: pointer; }
    .btn-text-danger { color: #f56c6c; background: none; border: none; cursor: pointer; }
    .dialog-overlay { position: fixed; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,0.5); display: flex; align-items: center; justify-content: center; z-index: 1000; }
    .dialog { background: #fff; padding: 20px; border-radius: 8px; width: 500px; }
    .dialog h3 { margin-bottom: 20px; }
    .form-group { margin-bottom: 15px; }
    .form-group label { display: block; margin-bottom: 5px; color: #606266; }
    .form-group input, .form-group select { width: 100%; padding: 8px 12px; border: 1px solid #dcdfe6; border-radius: 4px; }
    .dialog-footer { text-align: right; margin-top: 20px; }
    .dialog-footer button { margin-left: 10px; }
  `],
})
export class MenuComponent implements OnInit {
  menuList: any[] = [];
  queryParams = { menuName: '' };
  dialogVisible = false;
  dialogTitle = '';
  form: any = { id: undefined, parentId: 0, name: '', type: 0, path: '', component: '', permission: '', status: 0 };

  constructor(private api: ApiService) {}

  ngOnInit(): void {
    this.getList();
  }

  getList(): void {
    this.api.listMenu(this.queryParams).subscribe((res) => {
      this.menuList = res.data;
    });
  }

  handleAdd(parent?: any): void {
    this.dialogTitle = '新增菜单';
    this.form = { id: undefined, parentId: parent?.id || 0, name: '', type: parent ? 1 : 0, path: '', component: '', permission: '', status: 0 };
    this.dialogVisible = true;
  }

  handleUpdate(row: any): void {
    this.dialogTitle = '修改菜单';
    this.form = { ...row };
    this.dialogVisible = true;
  }

  handleDelete(row: any): void {
    if (confirm('确认删除该菜单?')) {
      this.api.deleteMenu(row.id).subscribe(() => this.getList());
    }
  }

  submitForm(): void {
    if (this.form.id) {
      this.api.updateMenu(this.form.id, this.form).subscribe(() => {
        this.dialogVisible = false;
        this.getList();
      });
    } else {
      this.api.addMenu(this.form).subscribe(() => {
        this.dialogVisible = false;
        this.getList();
      });
    }
  }
}

// vue-admin/src/views/system/menu/index.vue
<template>
  <div class="app-container">
    <el-form :model="queryParams" :inline="true">
      <el-form-item label="菜单名称">
        <el-input v-model="queryParams.menuName" placeholder="请输入菜单名称" @keyup.enter="handleQuery" />
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="handleQuery">搜索</el-button>
        <el-button @click="resetQuery">重置</el-button>
      </el-form-item>
    </el-form>

    <el-row :gutter="10" class="mb8">
      <el-col :span="1.5">
        <el-button type="primary" plain @click="handleAdd()">新增</el-button>
      </el-col>
    </el-row>

    <el-table
      v-loading="loading"
      :data="menuList"
      row-key="id"
      :tree-props="{ children: 'children' }"
      default-expand-all
    >
      <el-table-column prop="name" label="菜单名称" width="200" />
      <el-table-column prop="icon" label="图标" width="80">
        <template #default="scope">
          <el-icon v-if="scope.row.icon">
            <component :is="scope.row.icon" />
          </el-icon>
        </template>
      </el-table-column>
      <el-table-column prop="sort" label="排序" width="80" />
      <el-table-column prop="type" label="类型" width="80">
        <template #default="scope">
          <el-tag v-if="scope.row.type === 0">目录</el-tag>
          <el-tag v-else-if="scope.row.type === 1" type="success">菜单</el-tag>
          <el-tag v-else type="warning">按钮</el-tag>
        </template>
      </el-table-column>
      <el-table-column prop="path" label="路由路径" width="150" />
      <el-table-column prop="component" label="组件路径" width="200" />
      <el-table-column prop="permission" label="权限标识" width="150" />
      <el-table-column prop="status" label="状态" width="80">
        <template #default="scope">
          <el-tag :type="scope.row.status === 0 ? 'success' : 'danger'">
            {{ scope.row.status === 0 ? '正常' : '停用' }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="操作" width="200">
        <template #default="scope">
          <el-button link type="primary" @click="handleAdd(scope.row)">新增</el-button>
          <el-button link type="primary" @click="handleUpdate(scope.row)">修改</el-button>
          <el-button link type="primary" @click="handleDelete(scope.row)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-dialog :title="dialogTitle" v-model="dialogVisible" width="600px">
      <el-form ref="menuRef" :model="form" :rules="rules" label-width="100px">
        <el-row :gutter="20">
          <el-col :span="24">
            <el-form-item label="上级菜单">
              <el-tree-select
                v-model="form.parentId"
                :data="menuTreeOptions"
                :props="{ label: 'name', value: 'id', children: 'children' }"
                check-strictly
                placeholder="请选择上级菜单"
              />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="菜单类型" prop="type">
              <el-radio-group v-model="form.type">
                <el-radio :value="0">目录</el-radio>
                <el-radio :value="1">菜单</el-radio>
                <el-radio :value="2">按钮</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="菜单名称" prop="name">
              <el-input v-model="form.name" placeholder="请输入菜单名称" />
            </el-form-item>
          </el-col>
          <el-col :span="12" v-if="form.type !== 2">
            <el-form-item label="路由路径">
              <el-input v-model="form.path" placeholder="请输入路由路径" />
            </el-form-item>
          </el-col>
          <el-col :span="12" v-if="form.type === 1">
            <el-form-item label="组件路径">
              <el-input v-model="form.component" placeholder="请输入组件路径" />
            </el-form-item>
          </el-col>
          <el-col :span="12" v-if="form.type !== 0">
            <el-form-item label="权限标识">
              <el-input v-model="form.permission" placeholder="请输入权限标识" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="排序">
              <el-input-number v-model="form.sort" :min="0" />
            </el-form-item>
          </el-col>
          <el-col :span="12" v-if="form.type !== 2">
            <el-form-item label="图标">
              <el-input v-model="form.icon" placeholder="请输入图标名称" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="状态">
              <el-radio-group v-model="form.status">
                <el-radio :value="0">正常</el-radio>
                <el-radio :value="1">停用</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="submitForm">确定</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { listMenu, getMenu, addMenu, updateMenu, deleteMenu } from '@/api/system';

const loading = ref(false);
const menuList = ref<any[]>([]);
const menuTreeOptions = ref<any[]>([]);
const dialogVisible = ref(false);
const dialogTitle = ref('');

const queryParams = reactive({
  menuName: '',
});

const form = reactive({
  id: undefined as number | undefined,
  parentId: 0,
  name: '',
  path: '',
  component: '',
  icon: '',
  sort: 0,
  type: 0,
  permission: '',
  visible: 0,
  status: 0,
});

const rules = {
  name: [{ required: true, message: '请输入菜单名称', trigger: 'blur' }],
  type: [{ required: true, message: '请选择菜单类型', trigger: 'change' }],
};

const getList = async () => {
  loading.value = true;
  try {
    const res: any = await listMenu(queryParams);
    menuList.value = res.data;
    menuTreeOptions.value = [{ id: 0, name: '主类目', children: res.data }];
  } finally {
    loading.value = false;
  }
};

const handleQuery = () => getList();

const resetQuery = () => {
  queryParams.menuName = '';
  getList();
};

const handleAdd = (row?: any) => {
  dialogTitle.value = '新增菜单';
  Object.assign(form, {
    id: undefined,
    parentId: row?.id || 0,
    name: '',
    path: '',
    component: '',
    icon: '',
    sort: 0,
    type: row ? 1 : 0,
    permission: '',
    visible: 0,
    status: 0,
  });
  dialogVisible.value = true;
};

const handleUpdate = async (row: any) => {
  dialogTitle.value = '修改菜单';
  const res: any = await getMenu(row.id);
  Object.assign(form, res.data);
  dialogVisible.value = true;
};

const handleDelete = (row: any) => {
  ElMessageBox.confirm('确认删除该菜单?', '提示', { type: 'warning' }).then(async () => {
    await deleteMenu(row.id);
    ElMessage.success('删除成功');
    getList();
  });
};

const submitForm = async () => {
  if (form.id) {
    await updateMenu(form.id, form);
    ElMessage.success('修改成功');
  } else {
    await addMenu(form);
    ElMessage.success('新增成功');
  }
  dialogVisible.value = false;
  getList();
};

onMounted(() => getList());
</script>
