// angular-admin/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { appConfig } from '../../config/app.config';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="login-container">
      <div class="login-form">
        <h2 class="title">{{ title }}</h2>
        <div class="form-item">
          <input
            type="text"
            [(ngModel)]="username"
            placeholder="请输入用户名"
            (keyup.enter)="login()"
          />
        </div>
        <div class="form-item">
          <input
            type="password"
            [(ngModel)]="password"
            placeholder="请输入密码"
            (keyup.enter)="login()"
          />
        </div>
        <div *ngIf="error" class="error">{{ error }}</div>
        <button (click)="login()" [disabled]="loading" class="login-btn">
          {{ loading ? '登录中...' : '登录' }}
        </button>
      </div>
    </div>
  `,
  styles: [`
    .login-container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    }
    .login-form {
      width: 400px;
      padding: 40px;
      background: #fff;
      border-radius: 12px;
      box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
    }
    .title {
      text-align: center;
      margin-bottom: 30px;
      font-size: 24px;
      color: #333;
    }
    .form-item {
      margin-bottom: 20px;
    }
    input {
      width: 100%;
      padding: 12px;
      border: 1px solid #dcdfe6;
      border-radius: 4px;
      font-size: 14px;
      outline: none;
    }
    input:focus {
      border-color: #409eff;
    }
    .error {
      color: #f56c6c;
      font-size: 12px;
      margin-bottom: 10px;
    }
    .login-btn {
      width: 100%;
      padding: 12px;
      background: #409eff;
      color: #fff;
      border: none;
      border-radius: 4px;
      font-size: 16px;
      cursor: pointer;
    }
    .login-btn:hover {
      background: #66b1ff;
    }
    .login-btn:disabled {
      opacity: 0.7;
      cursor: not-allowed;
    }
  `],
})
export class LoginComponent {
  title = appConfig.title;
  username = 'admin';
  password = 'admin123';
  loading = false;
  error = '';

  constructor(private authService: AuthService, private router: Router) {}

  login(): void {
    if (!this.username || !this.password) {
      this.error = '请输入用户名和密码';
      return;
    }

    this.loading = true;
    this.error = '';

    this.authService.login(this.username, this.password).subscribe({
      next: () => {
        this.router.navigate(['/']);
      },
      error: (err) => {
        this.error = err.error?.message || '登录失败';
        this.loading = false;
      },
    });
  }
}

// next-admin/src/app/login/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Cookies from 'js-cookie';
import { appConfig } from '@/config/app';

export default function LoginPage() {
  const router = useRouter();
  const [username, setUsername] = useState('admin');
  const [password, setPassword] = useState('admin123');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    try {
      const res = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, password }),
      });

      const data = await res.json();

      if (data.code === 200) {
        Cookies.set('accessToken', data.data.accessToken, { expires: 1 });
        Cookies.set('refreshToken', data.data.refreshToken, { expires: 7 });
        localStorage.setItem('userInfo', JSON.stringify(data.data.user));
        router.push('/dashboard');
      } else {
        setError(data.message || '登录失败');
      }
    } catch {
      setError('网络错误');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-500 to-purple-600">
      <div className="bg-white dark:bg-gray-800 p-8 rounded-xl shadow-2xl w-96">
        <h1 className="text-2xl font-bold text-center mb-6 text-gray-800 dark:text-white">{appConfig.title}</h1>
        <form onSubmit={handleLogin}>
          {error && (
            <div className="mb-4 p-3 bg-red-100 text-red-700 rounded-lg text-sm">{error}</div>
          )}
          <div className="mb-4">
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">用户名</label>
            <input
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
              placeholder="请输入用户名"
            />
          </div>
          <div className="mb-6">
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">密码</label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
              placeholder="请输入密码"
            />
          </div>
          <button
            type="submit"
            disabled={loading}
            className="w-full bg-blue-500 text-white py-2 rounded-lg hover:bg-blue-600 transition duration-200 disabled:opacity-50"
          >
            {loading ? '登录中...' : '登录'}
          </button>
        </form>
      </div>
    </div>
  );
}
